import { describe, expect, it } from 'vitest';
import { ClassroomObservationLedgerStore } from '@/lib/fusion/classroom-observation-ledger';
import { CLASSROOM_CONTRACT_SCHEMA_VERSION } from '@/lib/fusion/contracts';

const event = { schemaVersion: CLASSROOM_CONTRACT_SCHEMA_VERSION, eventId: 'event-1', eventType: 'checkpoint_submitted' as const, lessonSessionId: 'lesson-1', courseId: 'course-1', sceneId: 'checkpoint-slope', correlationId: 'correlation-1', checkpointId: 'checkpoint-1', mappingId: 'map', mappingRevision: '1', lessonKnowledgePointIds: ['lesson-linear-function-slope'], originalQuestion: 'q', studentAnswer: 'a', localAssessment: { gradingMode: 'local', correctness: 'incorrect' as const }, occurredAt: '2026-07-24T00:00:00Z' };
const diagnosis = { schemaVersion: CLASSROOM_CONTRACT_SCHEMA_VERSION, eventId: 'event-1', correctness: 'incorrect' as const, diagnoses: [{ lessonKnowledgePointId: 'lesson-linear-function-slope', misconception: 'mismatch', confidence: 1 }], teachingIntent: { schemaVersion: CLASSROOM_CONTRACT_SCHEMA_VERSION, kind: 'insert_remediation' as const, targetLessonKnowledgePointIds: ['lesson-linear-function-slope'], recommendedStrategy: 'development_mock_concrete_example' }, warnings: [], createdAt: event.occurredAt };
const directive = { schemaVersion: CLASSROOM_CONTRACT_SCHEMA_VERSION, directiveId: 'directive-1', sourceEventId: 'event-1', kind: 'insert_remediation' as const, targetSceneId: 'remediate-slope-concrete', expectedRuntimeRevision: 0 };
describe('F12 classroom observation ledger', () => {
  it('projects minimal traceable observation facts and remains event/directive idempotent', () => { const store = new ClassroomObservationLedgerStore(); const first = store.record(event, diagnosis, directive, 'executed'); const duplicate = store.record(event, diagnosis, directive, 'executed'); expect(first.observations).toHaveLength(1); expect(duplicate.revision).toBe(1); expect(JSON.stringify(first)).not.toMatch(/token|cookie|memory|prompt|deeptutor_fusion_base_url/i); expect(first.observations[0]).toMatchObject({ sourceEventId: 'event-1', correlationId: 'correlation-1', diagnosisSummary: { correctness: 'incorrect', misconceptionCode: 'mismatch' }, directiveSummary: { executionStatus: 'executed' } }); });
  it('distinguishes diagnosis failure and unexecuted/degraded directive state', () => { const store = new ClassroomObservationLedgerStore(); const ledger = store.record(event, null, undefined, 'degraded'); expect(ledger.observations[0].diagnosisSummary).toBeUndefined(); expect(ledger.observations[0].directiveSummary).toBeUndefined(); });
});
